server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
#          uri:  git@github.com:potenco/springcloud-config.git #填写你自己的github路径
          uri:  https://github.com/potenco/springcloud-config.git #填写你自己的github路径
          search-paths:
            - springcloud-config
          username: ppotenco
          password: Ljy@123456
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'


